apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app600.f5k8s.net
  namespace: apps
spec:
  ingressClassName: nginx-plus
  rules:
  - host: app600.f5k8s.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1-svc
            port:
              number: 80
